export const RAG_CONFIG = {
  SEARCH_LIMIT: 10,
  CONTEXT_LIMIT: 5,
  SCORE_THRESHOLD: 0.3,
  RERANK_CANDIDATES: 10,
  AI_RERANK_LIMIT: 3,
  CHAT_SEARCH_LIMIT: 5,
  CHAT_CONTEXT_LIMIT: 3,
  CHAT_MEMORY_HINT_MESSAGES: 2,
} as const;
